# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppTestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppTestProject
  pod 'SwiftGen', '~> 6.0'
  pod 'lottie-ios'
  pod 'Toaster', '~>2.2'
  
  target 'AppTestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppTestProjectUITests' do
    # Pods for testing
  end

end
